# NumPy Learning

In [2]:
import numpy as np

- The Basics

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b = np.array([[2,35,5],[2,5,25]])
print(b)


[[ 2 35  5]
 [ 2  5 25]]


In [8]:
# Get Dimension
b.ndim

2

In [9]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get type
a.dtype

dtype('int32')

In [11]:
# Get Size
a.itemsize

4

In [13]:
# Get total size
a.size * a.itemsize

16

### Acessing/Changing specific elements, rows, colums, ets

In [15]:
a = np.array([[2342,2342,234],[2,52,5]])
print(a)

[[2342 2342  234]
 [   2   52    5]]


In [18]:
# Get Specific elenment [r,c]
a[1,2]

5

In [20]:
# Get row
a[0,:]

array([2342, 2342,  234])

In [21]:
# Get Colum
a[:,1]

array([2342,   52])

## 3D example

In [22]:
b = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [23]:
# Get specific element 
b[0,1,:]

array([3, 4])