In [8]:
import numpy as np
import matplotlib.pyplot as plt


In [12]:
def conv (x,h):
    lx = len(x)
    lh = len(h)
    y=np.zeros(lx+lh-1)
    
    for m in range(lx):
        for n in range(lh):
            y[m+n] = y[m+n] + x[m]*h[n]
        
    return y

In [13]:
x=[1,2,3,1]
h=[1,2,1,-1]
y= conv(x,h)
print(y)

d = np.zeros(1)
d[0] = 1

#identity property
yi = conv(x,d)
print(yi)

#commutative property
yc = conv(h,x)
print(yc)

[ 1.  4.  8.  8.  3. -2. -1.]
[1. 2. 3. 1.]
[ 1.  4.  8.  8.  3. -2. -1.]


In [14]:
z=np.convolve(x,h, 'full')
print(z)

[ 1  4  8  8  3 -2 -1]
