In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,34,5,25]])

In [3]:
myarr

array([[ 3, 34,  5, 25]])

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

# Array Creation

In [9]:
listarr = np.array([[1,2,3],[5,5,5],[2,5,1]])

In [10]:
listarr

array([[1, 2, 3],
       [5, 5, 5],
       [2, 5, 1]])

In [11]:
listarr.dtype

dtype('int32')

In [12]:
listarr.shape

(3, 3)

In [13]:
listarr.size

9

In [14]:
np.array({1,2,23,5})

array({1, 2, 5, 23}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace = np.linspace(1,4,7)
lspace

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [21]:
emp = np.empty((4,6))
emp

array([[1.27473092e-311, 1.27473470e-311, 1.27473470e-311,
        1.27473470e-311, 1.27473470e-311, 1.27473470e-311],
       [1.27473470e-311, 1.27473470e-311, 1.27473470e-311,
        1.27473470e-311, 1.27473470e-311, 1.27473470e-311],
       [1.27473470e-311, 1.27473470e-311, 1.27473470e-311,
        1.27473470e-311, 1.27473470e-311, 1.27473470e-311],
       [1.27473470e-311, 1.27473470e-311, 1.27473470e-311,
        1.27473470e-311, 1.27473470e-311, 1.27473470e-311]])

In [28]:
empLike = np.empty_like(lspace)
empLike

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [29]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.shape

(45, 45)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

In [37]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0)
ar.sum(axis=1)

array([ 6, 15, 24])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

36

In [51]:
one = np.array([1,2,3,425,25])

In [53]:
one.argmax()

3

In [54]:
one.argmin()

0

In [55]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [58]:
ar.argmin()

0

In [59]:
ar.argmax()

8

In [60]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [61]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [63]:
ar2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [65]:
ar * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [70]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [77]:
ar.sum()



45

In [78]:
ar.min()

1

In [80]:
type(np.where(ar>5))

tuple

In [81]:
np.count_nonzero(ar)

9

In [82]:
import sys

In [83]:
py_arr = [0,4,52,5]

In [84]:
np_arr = [0,4,52,5]

In [85]:
sys.getsizeof(1)*len(py_arr)

112