In [28]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np

In [29]:
data1 = pd.read_csv('KNN_tarin_test_data.csv')
data1
data=np.array(data1)
data
x,y=int(13),int(15)

In [30]:
dis=np.zeros(len(data))
dis

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
for i in range(len(data)):
    dis[i]=np.sqrt(((x-data[i,0])**2)+((y-data[i,1])**2))

In [32]:
dis
    
    

array([11.18033989, 12.80624847,  5.65685425,  5.83095189,  4.12310563,
        7.61577311,  5.09901951,  9.21954446,  8.06225775,  5.83095189])

In [25]:
new_data=np.insert(data,2,dis,axis=1)
new_data
new_data=sorted(new_data,key=lambda x:x[2])
new_data
c1,cz=0,0

In [26]:
for i in range(5):
    if new_data[i][3] == 1:
        c1 += 1
    else:
        cz += 1

In [27]:
print(c1,cz)
if c1 > cz:
    print('class 1')
else:
    print('class 0')

3 2
class 1


In [33]:
new_data

[array([14, 11,  4,  0], dtype=int64),
 array([ 9, 19,  5,  1], dtype=int64),
 array([ 8, 12,  5,  0], dtype=int64),
 array([12, 20,  5,  1], dtype=int64),
 array([18, 18,  5,  1], dtype=int64),
 array([10,  8,  7,  0], dtype=int64),
 array([17, 22,  8,  1], dtype=int64),
 array([20, 21,  9,  1], dtype=int64),
 array([ 3, 10, 11,  0], dtype=int64),
 array([ 5,  5, 12,  0], dtype=int64)]