In [7]:
#convulation sum EX: 2.3.2
#1st method
import numpy as np
import matplotlib.pyplot as plt

x = [1, 2, 3, 1]
h = [1, 2, 1, -1]
lx = len(x)
lh = len(h)
y = np.zeros(lx+lh-1)

for m in range(lx):
    for n in range(lh):
        y[m+n] = y[m+n] + x[m]*h[n]
print(y)

[ 1.  4.  8.  8.  3. -2. -1.]


In [8]:
#2nd method relates with 1st
z = np.convolve(x, h, 'full')
print(z)

[ 1  4  8  8  3 -2 -1]


In [9]:
#3rd method indivitual
import numpy as np
import matplotlib.pyplot as plt

x = [1, 2, 3, 1]
h = [1, 2, 1, -1]

z = np.convolve(x, h, 'full')
print(z)

[ 1  4  8  8  3 -2 -1]
