In [22]:
import numpy as np
import matplotlib.pyplot as plt

def conv(x, h):
    lx = len(x)
    lh = len(h)
    y = np.zeros(lx+lh-1)
    
    for m in range(lx):
        for n in range(lh):
            y[m+n] = y[m+n] + x[m]*h[n]
    return y
x = [1,2,3,1]
h = [1, 2, 1, -1]

y = conv(x, h)
print(y)

d = np.zeros(1)
d[0] = 1

#identity law
yi = conv(x, d)
print(yi)

#communitative property
yc = conv(h, x)
print(yc) 

#assosiative law 
h2 = [1,2 ,3, 1]
ya = conv(yc, h2)
print(ya) 

yb = conv(h2, yc)
print(yb)

#distributive law 
yd1 = conv(x, h + h2)
print(yd1)

yd2 = conv(x, h) + conv(x, h2)
print(yd2)


[ 1.  4.  8.  8.  3. -2. -1.]
[1. 2. 3. 1.]
[ 1.  4.  8.  8.  3. -2. -1.]
[ 1.  6. 19. 37. 47. 36. 12. -5. -5. -1.]
[ 1.  6. 19. 37. 47. 36. 12. -5. -5. -1.]
[ 1.  4.  8.  8.  4.  2.  9. 14. 13.  6.  1.]
[ 2.  8. 18. 22. 16.  4.  0.]
